/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consoleapp2;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        System.out.println("Heeeeeeeelooooooloooooo!!");
        App classUnderTest = new App();
        System.out.println("WOOOOOOOORLDDDDDDD!!");
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
